# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  owaspapi:
    image: owaspapi
    build:
      context: .
      dockerfile: owasp-api-src/Dockerfile
    ports:
      - 80